#Theme 1
Вычисления с помощью Numpy

##Task 1
Импортируйте библиотеку Numpy и дайте ей псевдоним np.
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.


In [ ]:
import numpy as np
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]]).T
print('Матрица наблюдения-признаки')
print(a)
a_mean = a.mean(axis=0)
print(f'Среднее по первому и второму признаку соответственно {a_mean[0]} и {a_mean[1]}')


Матрица наблюдения-признаки
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Среднее по первому и второму признаку соответственно 2.0 и 8.4


In [ ]:
a_mean

array([2. , 8.4])

##Task 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [ ]:
a_centered = a - a_mean
print('Центрированная матрица наблюдения-признаки')
print(a_centered)

Центрированная матрица наблюдения-признаки
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


##Task 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина a_centered_sp. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [ ]:
a_centered_sp = np.dot(a_centered[:,0], a_centered[:,1]) 
cov_home = a_centered_sp / (a_centered.shape[0]-1)
print(f'Несмещенная оценка ковариации "домашним" методом: {cov_home}')

Несмещенная оценка ковариации "домашним" методом: 2.0


##Task 4*
В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив “a”. В получившейся ковариационной матрице (массив Numpy размером 2x2) искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.

In [ ]:
cov = np.cov(a_centered.T)
print(f'Несмещенная оценка ковариации встроенной функцией np: {cov[0,1]}')

Несмещенная оценка ковариации встроенной функцией np: 2.0


In [ ]:
cov

array([[1. , 2. ],
       [2. , 4.3]])

##Task 5**
Необходимо реализовать метод сортировки целых (int) элементов. Метод должен быть реализован без использования “готовых” методов ( sorted, np.sort() ).

In [ ]:
def bubble_sort(a):
    for i in range(len(a)):
        for j in range(i, len(a)):
            if a[i]>a[j]:
                   a[i], a[j] = a[j], a[i]
    return a

In [ ]:
bubble_sort([300, 300, 400, 400, 5])

[5, 300, 300, 400, 400]

#Theme 2
Работа с данными в Pandas

##Task 1
Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм authors со столбцами author_id и author_name, в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].
Затем создайте датафрейм book cо столбцами author_id, book_title и price, в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3],
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
[450, 300, 350, 500, 450, 370, 290].


In [ ]:
import pandas as pd
d1 = {
    'author_id': [1, 2, 3], 
    'author_name':['Тургенев', 'Чехов', 'Островский']
    }
authors = pd.DataFrame(d1)

d2 = {
    'author_id': [1, 1, 1, 2, 2, 3, 3], 
    'book_title': ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 
                   'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
    'price':  [450, 300, 350, 500, 450, 370, 290]
    }
book = pd.DataFrame(d2)

print(authors)
print('\n')
print(book)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


##Task 2
Получите датафрейм authors_price, соединив датафреймы authors и books по полю author_id.


In [ ]:
authors_price = pd.merge(authors, book, on='author_id', how='left')
print(authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


##Task 3
Создайте датафрейм top5, в котором содержатся строки из authors_price с пятью самыми дорогими книгами.

In [ ]:
authors_price = authors_price.sort_values(by='price', ascending=False).reset_index(drop=True)
top5 = authors_price.head()
print(top5)

   author_id author_name         book_title  price
0          2       Чехов   Толстый и тонкий    500
1          1    Тургенев        Отцы и дети    450
2          2       Чехов    Дама с собачкой    450
3          3  Островский              Гроза    370
4          1    Тургенев  Дворянское гнездо    350


##Task 4
Создайте датафрейм authors_stat на основе информации из authors_price. В датафрейме authors_stat должны быть четыре столбца:
author_name, min_price, max_price и mean_price,
в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [ ]:
author_name = authors_price.groupby("author_name")
authors_stat = pd.DataFrame(author_name.agg({'price' : ['min', 'max', 'mean']})).reset_index()
authors_stat = authors_stat.rename(columns={'price': '_price'})
print(authors_stat)

  author_name _price                 
                 min  max        mean
0  Островский    290  370  330.000000
1    Тургенев    300  450  366.666667
2       Чехов    450  500  475.000000


In [ ]:
authors_stat.columns = authors_stat.columns.swaplevel()
authors_stat.columns = [''.join(col) for col in authors_stat.columns]
print(authors_stat)

  author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000


## Task 5*
Создайте новый столбец в датафрейме authors_price под названием cover, в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].
Просмотрите документацию по функции pd.pivot_table с помощью вопросительного знака.Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.
Назовите полученный датасет book_info и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его book_info2. Удостоверьтесь, что датафреймы book_info и book_info2 идентичны.


In [ ]:
authors_price

author_id author_name            book_title  price
0          2       Чехов      Толстый и тонкий    500
1          1    Тургенев           Отцы и дети    450
2          2       Чехов       Дама с собачкой    450
3          3  Островский                 Гроза    370
4          1    Тургенев     Дворянское гнездо    350
5          1    Тургенев                 Рудин    300
6          3  Островский  Таланты и поклонники    290

In [ ]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
print('Дополнили authors_price:')
print(authors_price)

book_info = pd.pivot_table(authors_price, values='price' , index='author_name',columns='cover', aggfunc=sum, fill_value=0)
print('\nПолучили book_info:')
print(book_info)

book_info.to_pickle('book_info.pkl')
book_info2 = pd.read_pickle('book_info.pkl')
print('\nПолучили book_info2:')
print(book_info2)

if book_info.equals(book_info2) and book_info.index.names == book_info2.index.names:
  print('\nОни идентичны!')


Дополнили authors_price:
   author_id author_name            book_title  price    cover
0          2       Чехов      Толстый и тонкий    500  твердая
1          1    Тургенев           Отцы и дети    450   мягкая
2          2       Чехов       Дама с собачкой    450   мягкая
3          3  Островский                 Гроза    370  твердая
4          1    Тургенев     Дворянское гнездо    350  твердая
5          1    Тургенев                 Рудин    300   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

Получили book_info:
cover        мягкая  твердая
author_name                 
Островский      290      370
Тургенев        750      350
Чехов           450      500

Получили book_info2:
cover        мягкая  твердая
author_name                 
Островский      290      370
Тургенев        750      350
Чехов           450      500

Они идентичны!


In [ ]:
book_info

cover        мягкая  твердая
author_name                 
Островский      290      370
Тургенев        750      350
Чехов           450      500

## Task 5**
Вычисление метрик для мониторинга.

1.   суммарная выручка
2.   кол-во покупок
3.   средний чек
4.   среднее кол-во товаров в покупке

Дополнительно добавим возможность фильтровать данные по различным параметрам. Это может быть полезно чтобы посмотреть как меняются продажи в двух группах, или в какой-то отдельной категории товаров.
На вход функции будет подаваться датафрейм с данными о продажах, словарь с фильтрами и период, за который нужно посчитать метрики.
Функция должна вернуть датафрейм, в индексах которого будут все даты из указанного периода отсортированные по возрастанию, а столбцы - метрики ['revenue', 'number_purchases', 'average_check', 'average_number_items']. Формат данных столбцов - float, формат данных индекса - datetime64[ns].
Если в какие-то дни не было продаж, то нужно заполнить пропуск нулём.

In [ ]:
data = pd.DataFrame(
            [[820, '2021-04-29', 1, 213],[100, '2021-04-29', 1, 213],
             [600, '2021-04-30', 2, 113],[700, '2021-05-01', 3, 893]],
            columns=['cost', 'date', 'sale_id', 'shop_id']
        )

In [ ]:
data

cost        date  sale_id  shop_id
0   820  2021-04-29        1      213
1   100  2021-04-29        1      213
2   600  2021-04-30        2      113
3   700  2021-05-01        3      893

In [ ]:
period_dict = {'begin': '2021-04-29', 'end': '2021-04-30'}

In [ ]:
filters_dict = {'shop_id': [213, 893], 'sale_id':[1,2]}

In [ ]:
filters_dict.items()

dict_items([('shop_id', [213, 893]), ('sale_id', [1, 2])])

In [ ]:
calculate_sales_metrics(data, 'cost', 'date', 'sale_id',period_dict)

[ True  True False False]


revenue  number_purchases  average_check  average_number_items
2021-04-29      920                 1            920                     2

In [ ]:
filters_dict = {'shop_id': [213], 'sale_id':[1,2]}
calculate_sales_metrics(data, 'cost', 'date', 'sale_id',period_dict, filters_dict)

[ True  True False False]


revenue  number_purchases  average_check  average_number_items
2021-04-29    920.0               1.0          920.0                   2.0
2021-04-30      0.0               0.0            0.0                   0.0

In [ ]:
import numpy as np
import pandas as pd


def calculate_sales_metrics(df, cost_name, date_name, sale_id_name, period, filters=None):
    """Вычисляет метрики по продажам.
    
    df - pd.DataFrame, датафрейм с данными. Пример
        pd.DataFrame(
            [[820, '2021-04-03', 1, 213]],
            columns=['cost', 'date', 'sale_id', 'shop_id']
        )
    cost_name - str, название столбца с стоимостью товара
    date_name - str, название столбца с датой покупки
    sale_id_name - str, название столбца с идентификатором покупки (в одной покупке может быть несколько товаров)
    period - dict, словать с датами начала и конца периода пилота и препилота.
        Пример, {'begin': '2020-01-01', 'end': '2020-01-08'}.
        Дата начала периода входит в полуинтервал, а дата окончания нет,
        то есть '2020-01-01' <= date < '2020-01-08'.
    filters - dict, словарь с фильтрами. Ключ - название поля, по которому фильтруем, значение - список значений,
        которые нужно оставить. Например, {'user_id': [111, 123, 943]}.
        Если None, то фильтровать не нужно.

    return - pd.DataFrame, в индексах все даты из указанного периода отсортированные по возрастанию, 
        столбцы - метрики ['revenue', 'number_purchases', 'average_check', 'average_number_items'].
    """
    period['begin'] = pd.to_datetime(period['begin'])
    period['end'] = pd.to_datetime(period['end'])
    df[date_name] = pd.to_datetime(df[date_name])

    mask = ((df[date_name] >= period['begin']) & (df[date_name] < period['end'])).values
    if filters:
        for column, values in filters.items():
            mask = mask & df[column].isin(values).values
    df_filtered = df.iloc[mask]

    dates = pd.date_range(start=period['begin'], end=period['end'], freq='D')
    dates = dates[dates < period['end']]
    df_dates = pd.DataFrame(index=dates)

    df_revenue = (
        df_filtered
        .groupby(date_name)[[cost_name]].sum()
        .rename(columns={cost_name: 'revenue'})
    )
    df_number_purchases = (
        df_filtered
        .groupby(date_name)[[sale_id_name]].nunique()
        .rename(columns={sale_id_name: 'number_purchases'})
    )
    df_average_check = (
        df_filtered 
        .groupby([date_name, sale_id_name])[[cost_name]].sum()
        .reset_index()
        .groupby(date_name)[[cost_name]].mean()
        .rename(columns={cost_name: 'average_check'})
    )
    df_average_number_items = (
        df_filtered
        .groupby([date_name, sale_id_name])[[cost_name]].count()
        .reset_index()
        .groupby(date_name)[[cost_name]].mean()
        .rename(columns={cost_name: 'average_number_items'})
    )
    list_df = [df_revenue, df_number_purchases, df_average_check, df_average_number_items]
    df_res = df_dates.copy()
    for df_ in list_df:
        df_res = pd.merge(df_res, df_, how='outer', left_index=True, right_index=True)
    df_res.sort_index(inplace=True)
    df_res.fillna(0, inplace=True)
    return df_res